{{- $app := "overseer" }}
{{- $ctx := (merge (dict "name" $app) $) }}
{{- $fullName := include "media-stack.app.fullname" $ctx }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "media-stack.labels" $ctx | nindent 4 }}
spec:
  replicas: {{ .Values.overseerr.replicaCount }}
  selector:
    matchLabels:
      {{- include "media-stack.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "media-stack.selectorLabels" $ctx | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "media-stack.serviceAccountName" $ctx }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "media-stack.fullname" . }}-config
      containers:
        - name: {{ $app }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.overseerr.image.repository }}:{{ .Values.overseerr.image.tag }}"
          env:
            {{- toYaml .Values.overseerr.env | nindent 12 }}
            - name: PORT
              value: "{{ .Values.overseerr.port }}"
          imagePullPolicy: {{ .Values.overseerr.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.overseerr.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            {{- toYaml .Values.overseerr.resources | nindent 12 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
