{{- $app := "sonarr" }}
{{- $ctx := (merge (dict "name" $app) $) }}
{{- $fullName := include "media-stack.app.fullname" $ctx }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "media-stack.labels" $ctx | nindent 4 }}
spec:
  replicas: {{ .Values.sonarr.replicaCount }}
  selector:
    matchLabels:
      {{- include "media-stack.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "media-stack.selectorLabels" $ctx | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "media-stack.serviceAccountName" $ctx }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "media-stack.fullname" . }}-config
        - name: downloads
          {{- .Values.global.mediaStorage | toYaml | nindent 10 }}
        - name: backups
          {{- include "media-stack.extendNfsPath" (merge (dict "appendPath" "sonarr/Backups") $) | fromYaml | toYaml | nindent 10}}
      containers:
        - name: {{ $app }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.sonarr.image.repository }}:{{ .Values.sonarr.image.tag }}"
          env:
            {{- toYaml .Values.sonarr.env | nindent 12 }}
          imagePullPolicy: {{ .Values.sonarr.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.sonarr.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: backups
              mountPath: /config/Backups
          resources:
            {{- toYaml .Values.sonarr.resources | nindent 12 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
